// <auto-generated />
using LoveSync.IdentityGateway.Data;
using LoveSync.IdentityGateway.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LoveSyncDbContext), typeof(LoveSyncDbContextModel))]
