// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LoveSync.IdentityGateway.Data.CompiledModels
{
    public partial class LoveSyncDbContextModel
    {
        private LoveSyncDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("510a3d40-62a3-4ff3-8b8a-0bae85457bc9"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var accessLevel = AccessLevelEntityType.Create(this);
            var user = UserEntityType.Create(this);

            UserEntityType.CreateForeignKey1(user, accessLevel);

            AccessLevelEntityType.CreateAnnotations(accessLevel);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "10.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
